accessKeyId="DummyID" 
accessKey="DummyKey"
bucketName="bucketwendycyn1"
LambdaRoleARN="arn:aws:iam::XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
StepRoleARN="arn:aws:iam::XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
AccountID="1234567890"
